name: markdown_widget
description: markdown_widget package.
version: 1.0.0
homepage: null

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #markdown data parser
  markdown: ^7.0.1
  #highlight code
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0

  # to click link
  url_launcher: ^6.1.9
  # to get the index number on scroll for listview
  visibility_detector: ^0.3.3
  # make listview available to jump to index
  scroll_to_index: ^3.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  build_runner: ^2.3.3
  path: ^1.8.2
flutter:
